Ci img build
cybozu/neco-ubuntu pull request #27
Opened 2018-08-07 05:24 UTC by OriishiTakahiro

# [neco-ubuntu] make iso, make cloudもCIする

## 課題内容  
neco-ubuntuでmake isoやmake cloudのチェックをCIでしてない。  
CIでチェックして毎回ビルド可能かどうかチェックする。

## 設計
.circleci/config.ymlのチェック対象にイメージのビルド作業を追加  
※ dockerコンテナ上でのビルド → VM上でのビルドに  
( make cloud中のresize-and-copy-in-qcow2でパーティションをマウントしており、コンテナ実行ではその権限がないため、ビルドがこける可能性 )

2018-08-07 06:17 UTC, mitsutaka requested changes

2018-08-07 06:17 UTC, mitsutaka commented on .circleci/config.yml
> +                      curl $GO_URL | sudo tar -C /usr/local -x -z -f -
12-16: 細かいですがindent levelを揃えてみましょう

2018-08-07 06:34 UTC, OriishiTakahiro commented on .circleci/config.yml
> +                      curl $GO_URL | sudo tar -C /usr/local -x -z -f -
これは失礼しました、インデントレベルを揃えました。
よろしくお願いします。

2018-08-07 07:01 UTC, mitsutaka commented
https://github.com/cybozu-go/sabakan/blob/master/.circleci/config.yml#L15

このあたりを参考にしてみましょう。`name:`以降を`run:`より下げれば動くはず。

2018-08-08 00:13 UTC, OriishiTakahiro commented
ありがとうございます。
インデント修正いたしました。

よろしくお願いします。

2018-08-08 00:18 UTC, mitsutaka approved these changes
lgtm

2018-08-08 00:18 UTC, merged